// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include "SimulationException.hpp"
#include "Cell.cppwg.hpp"
#include "Corner_2.cppwg.hpp"
#include "Facet_2.cppwg.hpp"
#include "MacroMesh_2_2.cppwg.hpp"
#include "MacroMesh_3_3.cppwg.hpp"
#include "Node_2.cppwg.hpp"
#include "Node_3.cppwg.hpp"
#include "AbstractMesh_2_2.cppwg.hpp"
#include "AbstractMesh_3_3.cppwg.hpp"
#include "PetscUtils.cppwg.hpp"
#include "PottsMesh_2.cppwg.hpp"
#include "PottsMesh_3.cppwg.hpp"
#include "MeshFactory_PottsMesh_2.cppwg.hpp"
#include "MeshFactory_PottsMesh_3.cppwg.hpp"
#include "Scene_2.cppwg.hpp"
#include "Scene_3.cppwg.hpp"

namespace py = pybind11;

PYBIND11_MODULE(_pycells_all, m)
{
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const SimulationException& e) {
            PyErr_SetString(PyExc_RuntimeError, e.GetMessage().c_str());
        }
    });

    register_Cell_class(m);
    register_Corner_2_class(m);
    register_Facet_2_class(m);
    register_MacroMesh_2_2_class(m);
    register_MacroMesh_3_3_class(m);
    register_Node_2_class(m);
    register_Node_3_class(m);
    register_AbstractMesh_2_2_class(m);
    register_AbstractMesh_3_3_class(m);
    register_PetscUtils_class(m);
    register_PottsMesh_2_class(m);
    register_PottsMesh_3_class(m);
    register_MeshFactory_PottsMesh_2_class(m);
    register_MeshFactory_PottsMesh_3_class(m);
    register_Scene_2_class(m);
    register_Scene_3_class(m);
}
