// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif
#include "SimulationException.hpp"
#ifdef __GNUC__
#pragma GCC visibility pop
#endif
#include "Cell.cppwg.hpp"
#include "Corner.cppwg.hpp"
#include "Facet.cppwg.hpp"
#include "MacroMesh.cppwg.hpp"
#include "Node.cppwg.hpp"
#include "AbstractMesh.cppwg.hpp"
#include "PetscUtils.cppwg.hpp"
#include "PottsMesh.cppwg.hpp"
#include "MeshFactory.cppwg.hpp"
#include "Scene.cppwg.hpp"

namespace py = pybind11;

PYBIND11_MODULE(_pycells_all, m)
{
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const SimulationException& e) {
            PyErr_SetString(PyExc_RuntimeError, e.GetMessage().c_str());
        }
    });

    register_Cell_class(m);
    register_Corner_2_class(m);
    register_Facet_2_class(m);
    register_MacroMesh_2_2_class(m);
    register_MacroMesh_3_3_class(m);
    register_Node_2_class(m);
    register_Node_3_class(m);
    register_AbstractMesh_2_2_class(m);
    register_AbstractMesh_3_3_class(m);
    register_PetscUtils_class(m);
    register_PottsMesh_2_class(m);
    register_PottsMesh_3_class(m);
    register_MeshFactory_PottsMesh_2_class(m);
    register_MeshFactory_PottsMesh_3_class(m);
    register_Scene_2_class(m);
    register_Scene_3_class(m);
}
