// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "AbstractSphericalMesh.hpp"

#include "AbstractSphericalMesh.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef AbstractSphericalMesh<2, 2> AbstractSphericalMesh_2_2;
typedef AbstractSphericalMesh<3, 3> AbstractSphericalMesh_3_3;
typedef unsigned int unsignedint;


class AbstractSphericalMesh_2_2_Overrides : public AbstractSphericalMesh_2_2
{
public:
    using AbstractSphericalMesh_2_2::AbstractSphericalMesh;
    unsigned int GetNumElements() const override
    {
        PYBIND11_OVERRIDE_PURE(
            unsignedint,
            AbstractSphericalMesh_2_2,
            GetNumElements,
            );
    }
};

void register_AbstractSphericalMesh_2_2_class(py::module &m)
{
    py::class_<AbstractSphericalMesh_2_2, AbstractSphericalMesh_2_2_Overrides, std::shared_ptr<AbstractSphericalMesh_2_2>, AbstractMesh<2, 2>>(m, "AbstractSphericalMesh_2_2")
        .def("GetNumElements",
            (unsigned int(AbstractSphericalMesh_2_2::*)() const) &AbstractSphericalMesh_2_2::GetNumElements,
            " ")
    ;
}


class AbstractSphericalMesh_3_3_Overrides : public AbstractSphericalMesh_3_3
{
public:
    using AbstractSphericalMesh_3_3::AbstractSphericalMesh;
    unsigned int GetNumElements() const override
    {
        PYBIND11_OVERRIDE_PURE(
            unsignedint,
            AbstractSphericalMesh_3_3,
            GetNumElements,
            );
    }
};

void register_AbstractSphericalMesh_3_3_class(py::module &m)
{
    py::class_<AbstractSphericalMesh_3_3, AbstractSphericalMesh_3_3_Overrides, std::shared_ptr<AbstractSphericalMesh_3_3>, AbstractMesh<3, 3>>(m, "AbstractSphericalMesh_3_3")
        .def("GetNumElements",
            (unsigned int(AbstractSphericalMesh_3_3::*)() const) &AbstractSphericalMesh_3_3::GetNumElements,
            " ")
    ;
}
