// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef AbstractSphericalMesh_hpp__cppwg_wrapper
#define AbstractSphericalMesh_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractSphericalMesh_2_2_class(pybind11::module &m);
void register_AbstractSphericalMesh_3_3_class(pybind11::module &m);
#endif // AbstractSphericalMesh_hpp__cppwg_wrapper
