// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef CellFactory_hpp__cppwg_wrapper
#define CellFactory_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellFactory_Cell_2_class(pybind11::module &m);
void register_CellFactory_Cell_3_class(pybind11::module &m);
#endif // CellFactory_hpp__cppwg_wrapper
