// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "Cell.hpp"
#include <memory>
#include "CellFactory.hpp"

#include "CellFactory.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef CellFactory<Cell, 2> CellFactory_Cell_2;
typedef CellFactory<Cell, 3> CellFactory_Cell_3;


void register_CellFactory_Cell_2_class(py::module &m)
{
    py::class_<CellFactory_Cell_2, std::shared_ptr<CellFactory_Cell_2>>(m, "CellFactory_Cell_2")
        .def(py::init<>())
        .def("GetDimension",
            (unsigned int(CellFactory_Cell_2::*)() const) &CellFactory_Cell_2::GetDimension,
            " ")
        .def("CreateCell",
            (unsigned int(CellFactory_Cell_2::*)()) &CellFactory_Cell_2::CreateCell,
            " ")
    ;
}


void register_CellFactory_Cell_3_class(py::module &m)
{
    py::class_<CellFactory_Cell_3, std::shared_ptr<CellFactory_Cell_3>>(m, "CellFactory_Cell_3")
        .def(py::init<>())
        .def("GetDimension",
            (unsigned int(CellFactory_Cell_3::*)() const) &CellFactory_Cell_3::GetDimension,
            " ")
        .def("CreateCell",
            (unsigned int(CellFactory_Cell_3::*)()) &CellFactory_Cell_3::CreateCell,
            " ")
    ;
}
