// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "Cell.hpp"

#include "Cell.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef Cell Cell;


void register_Cell_class(py::module &m)
{
    py::class_<Cell, std::shared_ptr<Cell>>(m, "Cell")
        .def(py::init<>())
        .def("GetCellId",
            (unsigned int(Cell::*)() const) &Cell::GetCellId,
            " ")
    ;
}
