// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "Corner.hpp"

#include "Corner.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef Corner<2> Corner_2;
typedef unsigned int unsignedint;


class Corner_2_Overrides : public Corner_2
{
public:
    using Corner_2::Corner;
    unsigned int GetNumSubs() const override
    {
        PYBIND11_OVERRIDE(
            unsignedint,
            Corner_2,
            GetNumSubs,
            );
    }
};

void register_Corner_2_class(py::module &m)
{
    py::class_<Corner_2, Corner_2_Overrides, std::shared_ptr<Corner_2>>(m, "Corner_2")
        .def(py::init<>())
        .def("GetNumSubs",
            (unsigned int(Corner_2::*)() const) &Corner_2::GetNumSubs,
            " ")
        .def("GetSub",
            (::Corner<1> *(Corner_2::*)(unsigned int) const) &Corner_2::GetSub,
            " ", py::arg("index"), py::return_value_policy::reference)
        .def("AddSub",
            (void(Corner_2::*)(::Corner<1> *)) &Corner_2::AddSub,
            " ", py::arg("pSub"))
    ;
}
