// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef Corner_2_hpp__cppwg_wrapper
#define Corner_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Corner_2_class(pybind11::module &m);
#endif // Corner_2_hpp__cppwg_wrapper
