// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "Facet.hpp"

#include "Facet.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef unsigned int unsignedint;

typedef Facet<2> Facet_2;

class Facet_2_Overrides : public Facet_2
{
public:
    using Facet_2::Facet;
    unsigned int GetNumFaces() const override
    {
        PYBIND11_OVERRIDE(
            unsignedint,
            Facet_2,
            GetNumFaces,
            );
    }
};

void register_Facet_2_class(py::module &m)
{
    py::class_<Facet_2, Facet_2_Overrides, std::shared_ptr<Facet_2>>(m, "Facet_2")
        .def(py::init<>())
        .def("GetNumFaces",
            (unsigned int(Facet_2::*)() const) &Facet_2::GetNumFaces,
            " ")
        .def("GetFace",
            (::Facet<1> *(Facet_2::*)(unsigned int) const) &Facet_2::GetFace,
            " ", py::arg("index"), py::return_value_policy::reference)
        .def("AddFace",
            (void(Facet_2::*)(::Facet<1> *)) &Facet_2::AddFace,
            " ", py::arg("pFace"))
    ;
}
