// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef Facet_hpp__cppwg_wrapper
#define Facet_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Facet_2_class(pybind11::module &m);
#endif // Facet_hpp__cppwg_wrapper
