// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "MacroMesh.hpp"

#include "MacroMesh_3_3.cppwg.hpp"

namespace py = pybind11;
typedef MacroMesh<3, 3> MacroMesh_3_3;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_MacroMesh_3_3_class(py::module &m)
{
    py::class_<MacroMesh_3_3, std::shared_ptr<MacroMesh_3_3>>(m, "MacroMesh_3_3")
        .def(py::init<>())
        .def("GetDimension",
            (unsigned int(MacroMesh_3_3::*)() const) &MacroMesh_3_3::GetDimension,
            " ")
    ;
}
