// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef MacroMesh_hpp__cppwg_wrapper
#define MacroMesh_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_MacroMesh_2_2_class(pybind11::module &m);
void register_MacroMesh_3_3_class(pybind11::module &m);
#endif // MacroMesh_hpp__cppwg_wrapper
