// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef MeshFactory_hpp__cppwg_wrapper
#define MeshFactory_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_MeshFactory_PottsMesh_2_class(pybind11::module &m);
void register_MeshFactory_PottsMesh_3_class(pybind11::module &m);
#endif // MeshFactory_hpp__cppwg_wrapper
