// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "PottsMesh.hpp"
#include <memory>
#include "MeshFactory.hpp"

#include "MeshFactory.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

typedef MeshFactory<PottsMesh<2>> MeshFactory_PottsMesh_2;

void register_MeshFactory_PottsMesh_2_class(py::module &m)
{
    py::class_<MeshFactory_PottsMesh_2, std::shared_ptr<MeshFactory_PottsMesh_2>>(m, "MeshFactory_PottsMesh_2")
        .def(py::init<>())
        .def("generateMesh",
            (::std::shared_ptr<PottsMesh<2>>(MeshFactory_PottsMesh_2::*)()) &MeshFactory_PottsMesh_2::generateMesh,
            " ")
    ;
}

typedef MeshFactory<PottsMesh<3>> MeshFactory_PottsMesh_3;

void register_MeshFactory_PottsMesh_3_class(py::module &m)
{
    py::class_<MeshFactory_PottsMesh_3, std::shared_ptr<MeshFactory_PottsMesh_3>>(m, "MeshFactory_PottsMesh_3")
        .def(py::init<>())
        .def("generateMesh",
            (::std::shared_ptr<PottsMesh<3>>(MeshFactory_PottsMesh_3::*)()) &MeshFactory_PottsMesh_3::generateMesh,
            " ")
    ;
}
