// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "caster_petsc.h"
#include <memory>
#include "PetscUtils.hpp"

#include "PetscUtils.cppwg.hpp"

namespace py = pybind11;
typedef PetscUtils PetscUtils;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_PetscUtils_class(py::module &m)
{
    py::class_<PetscUtils, std::shared_ptr<PetscUtils>>(m, "PetscUtils")
        .def(py::init<>())
        .def_static("Initialise",
            (void(*)()) &PetscUtils::Initialise,
            " ")
        .def_static("IsInitialised",
            (bool(*)()) &PetscUtils::IsInitialised,
            " ")
        .def_static("GetSize",
            (int(*)()) &PetscUtils::GetSize,
            " ")
        .def_static("GetRank",
            (int(*)()) &PetscUtils::GetRank,
            " ")
        .def_static("CreateVec",
            (::Vec(*)(int)) &PetscUtils::CreateVec,
            " ", py::arg("size"), py::return_value_policy::reference)
        .def_static("ThrowPetscError",
            (void(*)()) &PetscUtils::ThrowPetscError,
            " ")
    ;
}
