// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef PottsMesh_hpp__cppwg_wrapper
#define PottsMesh_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_PottsMesh_2_class(pybind11::module &m);
void register_PottsMesh_3_class(pybind11::module &m);
#endif // PottsMesh_hpp__cppwg_wrapper
