// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "PybindVTKTypeCaster.h"
#include <memory>
#include "Scene.hpp"

#include "Scene_2.cppwg.hpp"

namespace py = pybind11;
typedef Scene<2> Scene_2;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_Scene_2_class(py::module &m)
{
    py::class_<Scene_2, std::shared_ptr<Scene_2>>(m, "Scene_2")
        .def(py::init<>())
        .def("GetRenderer",
            (::vtkSmartPointer<vtkRenderer>(Scene_2::*)()) &Scene_2::GetRenderer,
            " ")
        .def_static("ThrowException",
            (void(*)()) &Scene_2::ThrowException,
            " ")
    ;
}
