// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef SphericalMesh_hpp__cppwg_wrapper
#define SphericalMesh_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_SphericalMesh_2_2_class(pybind11::module &m);
void register_SphericalMesh_3_3_class(pybind11::module &m);
#endif // SphericalMesh_hpp__cppwg_wrapper
