// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "SphericalMesh.hpp"

#include "SphericalMesh.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef SphericalMesh<2, 2> SphericalMesh_2_2;
typedef SphericalMesh<3, 3> SphericalMesh_3_3;
typedef unsigned int unsignedint;


class SphericalMesh_2_2_Overrides : public SphericalMesh_2_2
{
public:
    using SphericalMesh_2_2::SphericalMesh;
    void Scale(double const factor) override
    {
        PYBIND11_OVERRIDE(
            void,
            SphericalMesh_2_2,
            Scale,
            factor);
    }
    unsigned int GetNumElements() const override
    {
        PYBIND11_OVERRIDE(
            unsignedint,
            SphericalMesh_2_2,
            GetNumElements,
            );
    }
};

void register_SphericalMesh_2_2_class(py::module &m)
{
    py::class_<SphericalMesh_2_2, SphericalMesh_2_2_Overrides, std::shared_ptr<SphericalMesh_2_2>, AbstractSphericalMesh<2, 2>>(m, "SphericalMesh_2_2")
        .def(py::init<>())
    ;
}


class SphericalMesh_3_3_Overrides : public SphericalMesh_3_3
{
public:
    using SphericalMesh_3_3::SphericalMesh;
    void Scale(double const factor) override
    {
        PYBIND11_OVERRIDE(
            void,
            SphericalMesh_3_3,
            Scale,
            factor);
    }
    unsigned int GetNumElements() const override
    {
        PYBIND11_OVERRIDE(
            unsignedint,
            SphericalMesh_3_3,
            GetNumElements,
            );
    }
};

void register_SphericalMesh_3_3_class(py::module &m)
{
    py::class_<SphericalMesh_3_3, SphericalMesh_3_3_Overrides, std::shared_ptr<SphericalMesh_3_3>, AbstractSphericalMesh<3, 3>>(m, "SphericalMesh_3_3")
        .def(py::init<>())
    ;
}
