// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif
#include "ThrowingFunction.hpp"
#ifdef __GNUC__
#pragma GCC visibility pop
#endif
#include "wrapper_header_collection.cppwg.hpp"
#include "Shape.cppwg.hpp"
#include "Cuboid.cppwg.hpp"
#include "Rectangle.cppwg.hpp"

namespace py = pybind11;

PYBIND11_MODULE(_pyshapes_primitives, m)
{
    py::module_::import("pyshapes.geometry._pyshapes_geometry");

    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const ShapeException& e) {
            PyErr_SetString(PyExc_RuntimeError, e.GetMessage().c_str());
        }
    });

    register_Shape_2_class(m);
    register_Shape_3_class(m);
    register_Cuboid_class(m);
    register_Rectangle_class(m);
}
