// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "AbstractShape.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef AbstractShape<2> AbstractShape_2;
typedef AbstractShape<3> AbstractShape_3;
typedef ::std::vector<double> _std_vector_lt_double_gt_;


class AbstractShape_2_Overrides : public AbstractShape_2
{
public:
    using AbstractShape_2::AbstractShape;
    double GetArea() const override
    {
        PYBIND11_OVERRIDE_PURE(
            double,
            AbstractShape_2,
            GetArea,
            );
    }
    ::std::vector<double> GetBoundingBox() const override
    {
        PYBIND11_OVERRIDE_PURE(
            _std_vector_lt_double_gt_,
            AbstractShape_2,
            GetBoundingBox,
            );
    }
};

void register_AbstractShape_2_class(py::module &m)
{
    py::class_<AbstractShape_2, AbstractShape_2_Overrides, std::shared_ptr<AbstractShape_2>>(m, "AbstractShape_2")
        .def(py::init<>())
        .def("GetArea",
            (double(AbstractShape_2::*)() const) &AbstractShape_2::GetArea,
            " ")
        .def("GetBoundingBox",
            (::std::vector<double>(AbstractShape_2::*)() const) &AbstractShape_2::GetBoundingBox,
            " ")
    ;
}


class AbstractShape_3_Overrides : public AbstractShape_3
{
public:
    using AbstractShape_3::AbstractShape;
    double GetArea() const override
    {
        PYBIND11_OVERRIDE_PURE(
            double,
            AbstractShape_3,
            GetArea,
            );
    }
    ::std::vector<double> GetBoundingBox() const override
    {
        PYBIND11_OVERRIDE_PURE(
            _std_vector_lt_double_gt_,
            AbstractShape_3,
            GetBoundingBox,
            );
    }
};

void register_AbstractShape_3_class(py::module &m)
{
    py::class_<AbstractShape_3, AbstractShape_3_Overrides, std::shared_ptr<AbstractShape_3>>(m, "AbstractShape_3")
        .def(py::init<>())
        .def("GetArea",
            (double(AbstractShape_3::*)() const) &AbstractShape_3::GetArea,
            " ")
        .def("GetBoundingBox",
            (::std::vector<double>(AbstractShape_3::*)() const) &AbstractShape_3::GetBoundingBox,
            " ")
    ;
}
