// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef AbstractPolygon_hpp__cppwg_wrapper
#define AbstractPolygon_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractPolygon_2_class(pybind11::module &m);
void register_AbstractPolygon_3_class(pybind11::module &m);
#endif // AbstractPolygon_hpp__cppwg_wrapper
