// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef AbstractShape_hpp__cppwg_wrapper
#define AbstractShape_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractShape_2_class(pybind11::module &m);
void register_AbstractShape_3_class(pybind11::module &m);
#endif // AbstractShape_hpp__cppwg_wrapper
