// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "AbstractPolygon.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef AbstractPolygon<2> AbstractPolygon_2;
typedef AbstractPolygon<3> AbstractPolygon_3;
typedef unsigned int unsignedint;


class AbstractPolygon_2_Overrides : public AbstractPolygon_2
{
public:
    using AbstractPolygon_2::AbstractPolygon;
    unsigned int GetNumSides() const override
    {
        PYBIND11_OVERRIDE_PURE(
            unsignedint,
            AbstractPolygon_2,
            GetNumSides,
            );
    }
};

void register_AbstractPolygon_2_class(py::module &m)
{
    py::class_<AbstractPolygon_2, AbstractPolygon_2_Overrides, std::shared_ptr<AbstractPolygon_2>, AbstractShape<2>>(m, "AbstractPolygon_2")
        .def("GetNumSides",
            (unsigned int(AbstractPolygon_2::*)() const) &AbstractPolygon_2::GetNumSides,
            " ")
    ;
}


class AbstractPolygon_3_Overrides : public AbstractPolygon_3
{
public:
    using AbstractPolygon_3::AbstractPolygon;
    unsigned int GetNumSides() const override
    {
        PYBIND11_OVERRIDE_PURE(
            unsignedint,
            AbstractPolygon_3,
            GetNumSides,
            );
    }
};

void register_AbstractPolygon_3_class(py::module &m)
{
    py::class_<AbstractPolygon_3, AbstractPolygon_3_Overrides, std::shared_ptr<AbstractPolygon_3>, AbstractShape<3>>(m, "AbstractPolygon_3")
        .def("GetNumSides",
            (unsigned int(AbstractPolygon_3::*)() const) &AbstractPolygon_3::GetNumSides,
            " ")
    ;
}
