// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "RegularPolygon.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef RegularPolygon<2> RegularPolygon_2;
typedef RegularPolygon<3> RegularPolygon_3;
typedef ::std::vector<double> _std_vector_lt_double_gt_;
typedef unsigned int unsignedint;


class RegularPolygon_2_Overrides : public RegularPolygon_2
{
public:
    using RegularPolygon_2::RegularPolygon;
    double GetArea() const override
    {
        PYBIND11_OVERRIDE(
            double,
            RegularPolygon_2,
            GetArea,
            );
    }
    ::std::vector<double> GetBoundingBox() const override
    {
        PYBIND11_OVERRIDE(
            _std_vector_lt_double_gt_,
            RegularPolygon_2,
            GetBoundingBox,
            );
    }
    unsigned int GetNumSides() const override
    {
        PYBIND11_OVERRIDE(
            unsignedint,
            RegularPolygon_2,
            GetNumSides,
            );
    }
};

void register_RegularPolygon_2_class(py::module &m)
{
    py::class_<RegularPolygon_2, RegularPolygon_2_Overrides, std::shared_ptr<RegularPolygon_2>, AbstractPolygon<2>>(m, "RegularPolygon_2")
        .def(py::init<unsigned int, double>(), py::arg("numSides") = 4, py::arg("sideLength") = 1.0)
    ;
}


class RegularPolygon_3_Overrides : public RegularPolygon_3
{
public:
    using RegularPolygon_3::RegularPolygon;
    double GetArea() const override
    {
        PYBIND11_OVERRIDE(
            double,
            RegularPolygon_3,
            GetArea,
            );
    }
    ::std::vector<double> GetBoundingBox() const override
    {
        PYBIND11_OVERRIDE(
            _std_vector_lt_double_gt_,
            RegularPolygon_3,
            GetBoundingBox,
            );
    }
    unsigned int GetNumSides() const override
    {
        PYBIND11_OVERRIDE(
            unsignedint,
            RegularPolygon_3,
            GetNumSides,
            );
    }
};

void register_RegularPolygon_3_class(py::module &m)
{
    py::class_<RegularPolygon_3, RegularPolygon_3_Overrides, std::shared_ptr<RegularPolygon_3>, AbstractPolygon<3>>(m, "RegularPolygon_3")
        .def(py::init<unsigned int, double>(), py::arg("numSides") = 4, py::arg("sideLength") = 1.0)
    ;
}
