// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef RegularPolygon_hpp__cppwg_wrapper
#define RegularPolygon_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_RegularPolygon_2_class(pybind11::module &m);
void register_RegularPolygon_3_class(pybind11::module &m);
#endif // RegularPolygon_hpp__cppwg_wrapper
