// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "ShapeMetrics.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef ShapeMetrics ShapeMetrics;


void register_ShapeMetrics_class(py::module &m)
{
    py::class_<ShapeMetrics, std::shared_ptr<ShapeMetrics>>(m, "ShapeMetrics")
        .def(py::init<>())
        .def_readwrite("area", &ShapeMetrics::area)
        .def_readwrite("perimeter", &ShapeMetrics::perimeter)
        .def_readonly("dimension", &ShapeMetrics::dimension)
    ;
}
