// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef ShapeClassifier_hpp__cppwg_wrapper
#define ShapeClassifier_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ShapeClassifier_class(pybind11::module &m);
#endif // ShapeClassifier_hpp__cppwg_wrapper
