// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "ShapeClassifier.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef ShapeClassifier ShapeClassifier;


void register_ShapeClassifier_class(py::module &m)
{
    py::class_<ShapeClassifier, std::shared_ptr<ShapeClassifier>>(m, "ShapeClassifier")
        .def(py::init<>())
        .def("Describe",
            (::std::string(ShapeClassifier::*)(::ShapeKind) const) &ShapeClassifier::Describe,
            " ", py::arg("kind") = ::ShapeKind::CIRCLE)
        .def("GetHandedness",
            (::Handedness(ShapeClassifier::*)() const) &ShapeClassifier::GetHandedness,
            " ")
    ;
}
