// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef ShapeMetrics_hpp__cppwg_wrapper
#define ShapeMetrics_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ShapeMetrics_class(pybind11::module &m);
#endif // ShapeMetrics_hpp__cppwg_wrapper
