// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "SquareFeet.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef SquareFeet SquareFeet;


void register_SquareFeet_class(py::module &m)
{
    py::class_<SquareFeet, std::shared_ptr<SquareFeet>>(m, "SquareFeet")
        .def(py::init<>())
        .def("PerSquareMetre",
            (double(SquareFeet::*)() const) &SquareFeet::PerSquareMetre,
            " ")
    ;
}
