// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "SquareMetres.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef SquareMetres SquareMetres;


void register_SquareMetres_class(py::module &m)
{
    py::class_<SquareMetres, std::shared_ptr<SquareMetres>>(m, "SquareMetres")
        .def(py::init<>())
        .def("PerSquareMetre",
            (double(SquareMetres::*)() const) &SquareMetres::PerSquareMetre,
            " ")
    ;
}
