// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef SquareFeet_hpp__cppwg_wrapper
#define SquareFeet_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_SquareFeet_class(pybind11::module &m);
#endif // SquareFeet_hpp__cppwg_wrapper
