// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef SquareMetres_hpp__cppwg_wrapper
#define SquareMetres_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_SquareMetres_class(pybind11::module &m);
#endif // SquareMetres_hpp__cppwg_wrapper
