// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"
#include "AreaUnits.hpp"

#include "UnitSquare.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef UnitSquare UnitSquare;


void register_UnitSquare_class(py::module &m)
{
    py::class_<UnitSquare, std::shared_ptr<UnitSquare>>(m, "UnitSquare")
        .def(py::init<double>(), py::arg("side") = 1.0)
        .def("GetArea",
            (double(UnitSquare::*)() const) &UnitSquare::GetArea,
            " ")
        .def("GetAreaIn_SquareMetres", &UnitSquare::GetAreaIn<SquareMetres>)
        .def("GetAreaIn_SquareFeet", &UnitSquare::GetAreaIn<SquareFeet>)
    ;
}
