// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef UnitSquare_hpp__cppwg_wrapper
#define UnitSquare_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_UnitSquare_class(pybind11::module &m);
#endif // UnitSquare_hpp__cppwg_wrapper
