"""Generated by cppwg genpackage - do not edit.

Compiled-extension imports and TemplateClass subscript stubs for this
subpackage. Hand-written code (TemplateMethod attachments, package init,
curation) belongs in the sibling __init__.py, which does `from ._generated
import *`.
"""

from ._pyshapes_geometry import *
from pyshapes._syntax import TemplateClass


class Point(TemplateClass):
    _instantiations = {
        ("2",): Point_2,
        ("3",): Point_3,
    }
