// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef pyshapes_HEADERS_HPP_
#define pyshapes_HEADERS_HPP_

// Includes
#include "Cuboid.hpp"
#include "Point.hpp"
#include "Rectangle.hpp"
#include "Shape.hpp"
#include "SimpleMathFunctions.hpp"
#include "Square.hpp"
#include "ThrowingFunction.hpp"
#include "Triangle.hpp"

// Instantiate Template Classes
template class Point<2>;
template class Point<3>;
template class Shape<2>;
template class Shape<3>;

// Typedefs for nicer naming
namespace cppwg
{
    typedef Point<2> Point_2;
    typedef Point<3> Point_3;
    typedef Shape<2> Shape_2;
    typedef Shape<3> Shape_3;
} // namespace cppwg

#endif // pyshapes_HEADERS_HPP_
