"""Unit tests for cppwg.genpackage (the `cppwg genpackage` subcommand)."""

import sys

import pytest

import cppwg.__main__ as cppwg_main
from cppwg import genpackage


def _class(base, instantiations, templated=True):
    return {"base": base, "templated": templated, "instantiations": instantiations}


def _inst(args, py_name):
    return {"args": list(args), "py_name": py_name}


def test_key_repr_singleton_and_multi():
    assert genpackage._key_repr(["2"]) == '("2",)'
    assert genpackage._key_repr(["2", "2"]) == '("2", "2")'
    assert genpackage._key_repr(["Cell", "2"]) == '("Cell", "2")'


def test_stub_source():
    stub = genpackage._stub_source(
        "Point", [_inst(["2"], "Point_2"), _inst(["3"], "Point_3")]
    )
    assert stub == (
        "class Point(TemplateClass):\n"
        "    _instantiations = {\n"
        '        ("2",): Point_2,\n'
        '        ("3",): Point_3,\n'
        "    }"
    )


def test_stub_source_diagonal_shorthand():
    """A multi-arg diagonal instantiation gains a single-arg alias when opted in."""
    stub = genpackage._stub_source(
        "Element",
        [_inst(["2", "2"], "Element_2_2"), _inst(["1", "2"], "Element_1_2")],
        diagonal_shorthand=True,
    )
    # <2, 2> is diagonal -> add the Element[2] alias; <1, 2> is not -> no alias.
    assert '("2", "2"): Element_2_2,' in stub
    assert '("2",): Element_2_2,' in stub
    assert '("1", "2"): Element_1_2,' in stub
    assert '("1",):' not in stub
    # Off by default: no aliases.
    plain = genpackage._stub_source("Element", [_inst(["2", "2"], "Element_2_2")])
    assert '("2",):' not in plain


def test_stub_source_nested_templated_arg():
    """A templated-type argument is keyed by its Python concrete class name."""
    # MeshFactory<PottsMesh<2>> -> key ("PottsMesh_2",), not ("PottsMesh<2>",),
    # so MeshFactory[PottsMesh[2]] resolves (PottsMesh[2] is the PottsMesh_2 class).
    cxx_to_pyname = {"PottsMesh<2>": "PottsMesh_2", "PottsMesh<3>": "PottsMesh_3"}
    stub = genpackage._stub_source(
        "MeshFactory",
        [
            _inst(["PottsMesh<2>"], "MeshFactory_PottsMesh_2"),
            _inst(["PottsMesh<3>"], "MeshFactory_PottsMesh_3"),
        ],
        cxx_to_pyname=cxx_to_pyname,
    )
    assert '("PottsMesh_2",): MeshFactory_PottsMesh_2,' in stub
    assert '("PottsMesh_3",): MeshFactory_PottsMesh_3,' in stub
    assert "<" not in stub  # the raw C++ type string is gone


def test_build_cxx_index():
    model = {
        "modules": [
            {
                "classes": [
                    _class("PottsMesh", [_inst(["2"], "PottsMesh_2")]),
                    _class("Cell", [_inst([], "Cell")], templated=False),
                ]
            }
        ]
    }
    index = genpackage._build_cxx_index(model)
    assert index == {"PottsMesh<2>": "PottsMesh_2"}  # untemplated Cell has no <...>


def test_render_generated_module_with_stub_imports_syntax():
    point = _class("Point", [_inst(["2"], "Point_2"), _inst(["3"], "Point_3")])
    content = genpackage.render_generated_module(
        "pyshapes", "from ._pyshapes_geometry import *", [point], [point]
    )
    assert content.startswith('"""Generated by tools/cppwg_genpackage.py')
    assert "from ._pyshapes_geometry import *" in content
    assert "from pyshapes._syntax import TemplateClass" in content
    assert "class Point(TemplateClass):" in content
    assert content.endswith("\n")


def test_render_generated_module_no_templates_omits_syntax():
    plain = _class("Square", [_inst([], "Square")], templated=False)
    content = genpackage.render_generated_module(
        "pyshapes", "from ._pyshapes_composites import *", [plain], []
    )
    assert "from ._pyshapes_composites import *" in content
    assert "import TemplateClass" not in content  # no templated -> no syntax import


def test_generate_module_per_subpackage(tmp_path):
    model = {
        "package": "pyshapes",
        "modules": [
            {
                "name": "geometry",
                "compiled_module": "_pyshapes_geometry",
                "imports": [],
                "classes": [
                    _class("Point", [_inst(["2"], "Point_2"), _inst(["3"], "Point_3")])
                ],
                "enums": [],
                "free_functions": [],
            },
            {
                "name": "math_funcs",
                "compiled_module": "_pyshapes_math_funcs",
                "imports": [],
                "classes": [],
                "enums": [],
                "free_functions": ["add"],
            },
        ],
    }
    layout = {"package": "pyshapes", "package_root": str(tmp_path)}

    genpackage.generate_module_per_subpackage(model, layout, overwrite=False)

    geometry = (tmp_path / "geometry" / "_generated.py").read_text()
    assert "from ._pyshapes_geometry import *" in geometry
    assert "class Point(TemplateClass):" in geometry

    math_funcs = (tmp_path / "math_funcs" / "_generated.py").read_text()
    assert "from ._pyshapes_math_funcs import *" in math_funcs
    assert "import TemplateClass" not in math_funcs  # free functions only


def test_module_dirs_override_places_single_module_at_root(tmp_path):
    """A `module_dirs` entry redirects a module's _generated.py (e.g. cells' root)."""
    model = {
        "package": "pycells",
        "modules": [
            {
                "name": "all",
                "compiled_module": "_pycells_all",
                "imports": [],
                "classes": [_class("Node", [_inst(["2"], "Node_2")])],
                "enums": [],
                "free_functions": [],
            }
        ],
    }
    layout = {"package_root": str(tmp_path), "module_dirs": {"all": "."}}

    genpackage.generate_module_per_subpackage(model, layout, overwrite=False)

    generated = (tmp_path / "_generated.py").read_text()  # at the root, not all/
    assert "from ._pycells_all import *" in generated
    assert "class Node(TemplateClass):" in generated


def test_generate_shared_module_split(tmp_path, capsys):
    """Split one shared extension into subpackages by an explicit membership list."""
    model = {
        "package": "pychaste",
        "modules": [
            {
                "name": "all",
                "compiled_module": "_pychaste_all",
                "imports": [],
                "classes": [
                    _class("Node", [_inst(["2"], "Node_2"), _inst(["3"], "Node_3")]),
                    _class("FileFinder", [_inst([], "FileFinder")], templated=False),
                    _class("PottsMesh", [_inst(["2"], "PottsMesh_2")]),
                ],
                "enums": ["RelativeTo"],
                "free_functions": [],
            }
        ],
    }
    layout = {
        "package": "chaste",
        "package_root": str(tmp_path),
        "compiled_module": "_pychaste_all",
        "subpackages": {
            "core": ["FileFinder", "RelativeTo"],
            "mesh": ["Node", "PottsMesh"],
        },
    }

    genpackage.generate_shared_module_split(model, layout, overwrite=False)

    core = (tmp_path / "core" / "_generated.py").read_text()
    assert "from chaste._pychaste_all import (" in core
    assert "FileFinder," in core and "RelativeTo," in core
    assert "import TemplateClass" not in core  # core has no templated class

    mesh = (tmp_path / "mesh" / "_generated.py").read_text()
    assert "from chaste._pychaste_all import (" in mesh
    # concrete names imported, sorted
    assert "Node_2," in mesh and "Node_3," in mesh and "PottsMesh_2," in mesh
    assert "from chaste._syntax import TemplateClass" in mesh
    assert "class Node(TemplateClass):" in mesh
    assert "class PottsMesh(TemplateClass):" in mesh


def test_flatten_to_root(tmp_path):
    """flatten_to_root emits a top-level _generated.py re-exporting every name."""
    model = {
        "package": "pychaste",
        "modules": [
            {
                "name": "all",
                "compiled_module": "_pychaste_all",
                "imports": [],
                "classes": [
                    _class("Node", [_inst(["2"], "Node_2")]),
                    _class("FileFinder", [_inst([], "FileFinder")], templated=False),
                ],
                "enums": ["RelativeTo"],
                "free_functions": [],
            }
        ],
    }
    layout = {
        "package": "chaste",
        "package_root": str(tmp_path),
        "compiled_module": "_pychaste_all",
        "flatten_to_root": True,
        "subpackages": {"core": ["FileFinder", "RelativeTo"], "mesh": ["Node"]},
    }

    genpackage.generate_shared_module_split(model, layout, overwrite=False)

    root = (tmp_path / "_generated.py").read_text()
    # Re-exports the base/enum names (not the concrete Node_2) from each subpackage.
    assert "from chaste.core import (" in root
    assert "from chaste.mesh import (" in root
    assert "FileFinder," in root and "RelativeTo," in root and "Node," in root
    assert "Node_2" not in root  # the stub name is flattened, not the concrete
    assert '"FileFinder",' in root and '"Node",' in root  # __all__
    assert "__all__ = [" in root


def test_flatten_to_root_warns_on_name_clash(tmp_path, capsys):
    """A base name exported by two subpackages is flagged as ambiguous."""
    model = {
        "package": "pkg",
        "modules": [
            {
                "name": "all",
                "compiled_module": "_pkg_all",
                "imports": [],
                "classes": [_class("Dup", [_inst([], "Dup")], templated=False)],
                "enums": [],
                "free_functions": [],
            }
        ],
    }
    layout = {
        "package": "pkg",
        "package_root": str(tmp_path),
        "compiled_module": "_pkg_all",
        "flatten_to_root": True,
        "subpackages": {"a": ["Dup"], "b": ["Dup"]},
    }

    genpackage.generate_shared_module_split(model, layout, overwrite=False)
    assert "'Dup'" in capsys.readouterr().err  # ambiguous top-level export


def test_shared_split_warns_on_unknown_and_unassigned(tmp_path, capsys):
    model = {
        "package": "pkg",
        "modules": [
            {
                "name": "all",
                "compiled_module": "_pkg_all",
                "imports": [],
                "classes": [
                    _class("Kept", [_inst([], "Kept")], templated=False),
                    _class("Orphan", [_inst([], "Orphan")], templated=False),
                ],
                "enums": [],
                "free_functions": [],
            }
        ],
    }
    layout = {
        "package": "pkg",
        "package_root": str(tmp_path),
        "compiled_module": "_pkg_all",
        "subpackages": {"sub": ["Kept", "DoesNotExist"]},
    }

    genpackage.generate_shared_module_split(model, layout, overwrite=False)

    err = capsys.readouterr().err
    assert "'DoesNotExist'" in err  # listed but not in model
    assert "'Orphan'" in err  # in model but not assigned to a subpackage


def test_main_dispatches_genpackage_subcommand(monkeypatch):
    """`cppwg genpackage ...` routes to genpackage.main with the remaining args."""
    captured = {}

    def fake_genpackage_main(argv):
        captured["argv"] = argv
        return 0

    monkeypatch.setattr(genpackage, "main", fake_genpackage_main)
    monkeypatch.setattr(
        sys, "argv", ["cppwg", "genpackage", "--model", "m.yaml", "--layout", "l.yaml"]
    )

    with pytest.raises(SystemExit) as exc_info:
        cppwg_main.main()

    assert exc_info.value.code == 0
    # The "genpackage" token is stripped; only the sub-args reach genpackage.main.
    assert captured["argv"] == ["--model", "m.yaml", "--layout", "l.yaml"]
