// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif
#include "ThrowingFunction.hpp"
#ifdef __GNUC__
#pragma GCC visibility pop
#endif
#include "wrapper_header_collection.cppwg.hpp"

namespace py = pybind11;

PYBIND11_MODULE(_pyshapes_math_funcs, m)
{
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const ShapeException& e) {
            PyErr_SetString(PyExc_RuntimeError, e.GetMessage().c_str());
        }
    });

    m.def("add", &add, " ", py::arg("i") = 1.0, py::arg("j") = 2.0);
    m.def("throw_exception", &throw_exception, " ");
    m.def("throw_unwrapped_exception", &throw_unwrapped_exception, " ");
}
