// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include "wrapper_header_collection.cppwg.hpp"
#include "Square.cppwg.hpp"

namespace py = pybind11;

PYBIND11_MODULE(_pyshapes_composites, m)
{
    py::module_::import("pyshapes.primitives._pyshapes_primitives");

    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const ShapeException& e) {
            PyErr_SetString(PyExc_RuntimeError, e.GetMessage().c_str());
        }
    });

    register_Square_class(m);
}
