// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "Square.cppwg.hpp"

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
typedef Square Square;


void register_Square_class(py::module &m)
{
    py::class_<Square, std::shared_ptr<Square>, ::Rectangle>(m, "Square")
        .def(py::init<double>(), py::arg("width") = 2.0)
    ;
}
