// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef Square_hpp__cppwg_wrapper
#define Square_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Square_class(pybind11::module &m);
#endif // Square_hpp__cppwg_wrapper
