#
# cppwg documentation build configuration file, created by
# sphinx-quickstart on Fri Jul  7 09:26:24 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "myst_parser",  # author pages in Markdown instead of reStructuredText
    "sphinx_copybutton",  # add a copy button to code blocks
]

# MyST (Markdown) niceties: ::: fenced directives and (# anchor)= header targets.
myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

# Strip common interactive prompts from the copied text so pasting a shell or
# Python snippet doesn't include the "$ " / ">>> " markers. Our fences don't use
# prompts today, but this keeps copy-paste clean if any are added later.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "cppwg"
copyright = "2017, J. Grogan"
author = "J. Grogan, Joe Bloggs, Chaste Developers <chaste-users@maillist.ox.ac.uk>"

# The version info for the project, used as replacement for |version| and
# |release|. Single-sourced from the installed package metadata (which pip
# populates from pyproject.toml) so it can never drift from the release; falls
# back to parsing pyproject.toml directly for a bare, uninstalled checkout.
def _project_version() -> str:
    from importlib import metadata

    try:
        return metadata.version("cppwg")
    except metadata.PackageNotFoundError:
        # Bare, uninstalled checkout: read the version straight from pyproject.
        # Parse with a small regex rather than tomllib, which is stdlib only on
        # Python >= 3.11 while this project supports >= 3.10 (importing tomllib
        # would crash the fallback on 3.10). The `version = "..."` line anchored
        # to the start of a line is unambiguous (e.g. `target-version` does not
        # match).
        import re

        pyproject = os.path.join(os.path.dirname(__file__), os.pardir, "pyproject.toml")
        with open(pyproject, encoding="utf-8") as fh:
            match = re.search(r'(?m)^version\s*=\s*"([^"]+)"', fh.read())
        return match.group(1) if match else "0.0.0"


# The full version, including alpha/beta/rc tags.
release = _project_version()
# The short X.Y version.
version = ".".join(release.split(".")[:2])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Leave the Pygments style unset so Furo applies its own syntax highlighting.
# pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Project title shown in the sidebar.
html_title = f"{project} documentation"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []



# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "cppwgdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "cppwg.tex", "cppwg Documentation", author, "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "cppwg", "cppwg Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "cppwg",
        "cppwg Documentation",
        author,
        "cppwg",
        "An automatic Python wrapper generator for C++ code.",
        "Miscellaneous",
    ),
]
