"""Generated by cppwg genpackage - do not edit.

Compiled-extension imports and TemplateClass subscript stubs for this
subpackage. Hand-written code (TemplateMethod attachments, package init,
curation) belongs in the sibling __init__.py, which does `from ._generated
import *`.
"""

from ._pycells_all import (
    AbstractMesh_2_2,
    AbstractMesh_3_3,
    AbstractSphericalMesh_2_2,
    AbstractSphericalMesh_3_3,
    Cell,
    CellFactory_Cell_2,
    CellFactory_Cell_3,
    Corner_2,
    Facet_2,
    MacroMesh_2_2,
    MacroMesh_3_3,
    MeshFactory_PottsMesh_2,
    MeshFactory_PottsMesh_3,
    Node_2,
    Node_3,
    PetscUtils,
    PottsMesh_2,
    PottsMesh_3,
    Scene_2,
    Scene_3,
    SphericalMesh_2_2,
    SphericalMesh_3_3,
)
from pycells._syntax import TemplateClass

__all__ = [
    "AbstractMesh",
    "AbstractMesh_2_2",
    "AbstractMesh_3_3",
    "AbstractSphericalMesh",
    "AbstractSphericalMesh_2_2",
    "AbstractSphericalMesh_3_3",
    "Cell",
    "CellFactory",
    "CellFactory_Cell_2",
    "CellFactory_Cell_3",
    "Corner",
    "Corner_2",
    "Facet",
    "Facet_2",
    "MacroMesh",
    "MacroMesh_2_2",
    "MacroMesh_3_3",
    "MeshFactory",
    "MeshFactory_PottsMesh_2",
    "MeshFactory_PottsMesh_3",
    "Node",
    "Node_2",
    "Node_3",
    "PetscUtils",
    "PottsMesh",
    "PottsMesh_2",
    "PottsMesh_3",
    "Scene",
    "Scene_2",
    "Scene_3",
    "SphericalMesh",
    "SphericalMesh_2_2",
    "SphericalMesh_3_3",
]


class CellFactory(TemplateClass):
    _instantiations = {
        ("Cell", "2"): CellFactory_Cell_2,
        ("Cell", "3"): CellFactory_Cell_3,
    }


class Corner(TemplateClass):
    _instantiations = {
        ("2",): Corner_2,
    }


class Facet(TemplateClass):
    _instantiations = {
        ("2",): Facet_2,
    }


class MacroMesh(TemplateClass):
    _instantiations = {
        ("2", "2"): MacroMesh_2_2,
        ("3", "3"): MacroMesh_3_3,
    }


class Node(TemplateClass):
    _instantiations = {
        ("2",): Node_2,
        ("3",): Node_3,
    }


class AbstractMesh(TemplateClass):
    _instantiations = {
        ("2", "2"): AbstractMesh_2_2,
        ("3", "3"): AbstractMesh_3_3,
    }


class AbstractSphericalMesh(TemplateClass):
    _instantiations = {
        ("2", "2"): AbstractSphericalMesh_2_2,
        ("3", "3"): AbstractSphericalMesh_3_3,
    }


class PottsMesh(TemplateClass):
    _instantiations = {
        ("2",): PottsMesh_2,
        ("3",): PottsMesh_3,
    }


class MeshFactory(TemplateClass):
    _instantiations = {
        ("PottsMesh_2",): MeshFactory_PottsMesh_2,
        ("PottsMesh_3",): MeshFactory_PottsMesh_3,
    }


class Scene(TemplateClass):
    _instantiations = {
        ("2",): Scene_2,
        ("3",): Scene_3,
    }


class SphericalMesh(TemplateClass):
    _instantiations = {
        ("2", "2"): SphericalMesh_2_2,
        ("3", "3"): SphericalMesh_3_3,
    }
