schema_version: 1

context:
  version: "0.0.1"

package:
  name: pycells
  version: ${{ version }}

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - boost-cpp
    - mpi4py
    - openmpi
    - petsc
    - petsc4py
    - pip
    - python
    - scikit-build-core
    - vtk

tests:
  - python:
      imports:
        - pycells
      pip_check: false

about:
  license: BSD-3-Clause
