# The compiled-extension imports and TemplateClass stubs are generated by
# cppwg genpackage into _generated.py; add any hand-written code here.
from ._generated import *  # noqa: F401,F403
from pyshapes._syntax import TemplateMethod

# UnitSquare::GetAreaIn<UNIT>() is a templated method (see GetAreaInCustomTemplate.py);
# expose its per-unit bindings as GetAreaIn[Unit](). GetAreaIn is also a plain
# overload (GetAreaIn(perSquareMetre)); pass it as the fallback so the descriptor
# does not shadow it and UnitSquare.GetAreaIn(factor) keeps working.
# (TemplateMethod attachments cannot be auto-generated, so they live here.)
UnitSquare.GetAreaIn = TemplateMethod("GetAreaIn", UnitSquare.GetAreaIn)
