"""Generated by tools/cppwg_initgen.py - do not edit.

Compiled-extension imports and TemplateClass subscript stubs for this
subpackage. Hand-written code (TemplateMethod attachments, package init,
curation) belongs in the sibling __init__.py, which does `from ._generated
import *`.
"""

from ._pyshapes_primitives import *
from pyshapes._syntax import TemplateClass


class AbstractShape(TemplateClass):
    _instantiations = {
        ("2",): AbstractShape_2,
        ("3",): AbstractShape_3,
    }


class AbstractPolygon(TemplateClass):
    _instantiations = {
        ("2",): AbstractPolygon_2,
        ("3",): AbstractPolygon_3,
    }


class RegularPolygon(TemplateClass):
    _instantiations = {
        ("2",): RegularPolygon_2,
        ("3",): RegularPolygon_3,
    }


class Shape(TemplateClass):
    _instantiations = {
        ("2",): Shape_2,
        ("3",): Shape_3,
    }
