"""Generated by cppwg genpackage - do not edit.

Compiled-extension imports and TemplateClass subscript stubs for this
subpackage. Hand-written code (TemplateMethod attachments, package init,
curation) belongs in the sibling __init__.py, which does `from ._generated
import *`.
"""

from ._pyshapes_primitives import (
    CIRCLE,
    Cuboid,
    Handedness,
    Rectangle,
    RegularPolygon_2,
    RegularPolygon_3,
    SQUARE,
    ShapeClassifier,
    ShapeKind,
    ShapeMetrics,
    Shape_2,
    Shape_3,
    SquareFeet,
    SquareMetres,
    TRIANGLE,
    UnitSquare,
)
from pyshapes._syntax import TemplateClass

__all__ = [
    "CIRCLE",
    "Cuboid",
    "Handedness",
    "Rectangle",
    "RegularPolygon",
    "RegularPolygon_2",
    "RegularPolygon_3",
    "SQUARE",
    "Shape",
    "ShapeClassifier",
    "ShapeKind",
    "ShapeMetrics",
    "Shape_2",
    "Shape_3",
    "SquareFeet",
    "SquareMetres",
    "TRIANGLE",
    "UnitSquare",
]


class RegularPolygon(TemplateClass):
    _instantiations = {
        ("2",): RegularPolygon_2,
        ("3",): RegularPolygon_3,
    }


class Shape(TemplateClass):
    _instantiations = {
        ("2",): Shape_2,
        ("3",): Shape_3,
    }
