#!/usr/bin/env python3
"""Generate the Python package layer (``_generated.py``) for a cppwg project.

cppwg generates the C++/pybind11 wrappers and, alongside them, a JSON model of
what it produced (``cppwg_package_model.json`` in the wrapper root - see
``cppwg.utils.package_model``). This module (run via ``cppwg genpackage``) turns
that model, plus a small package-layout file, into a ``_generated.py`` per
Python subpackage: the
compiled-extension import and the ``TemplateClass`` subscript stubs
(``Point[2] -> Point_2``). It never touches the hand-written ``__init__.py``,
which does ``from ._generated import *`` and adds the bespoke pieces
(``TemplateMethod`` attachments, package ``init()``, curation, comments).

Two layouts:

* module-per-subpackage (default): each cppwg module becomes a subpackage that
  owns its own compiled extension, imported with ``from .<module> import *``.
  Used by the shapes/cells examples.
* shared-module split: one compiled extension (e.g. ``_pychaste_all``) is split
  into several subpackages by a layout that lists which names each owns;
  imported explicitly with ``from <package>.<module> import (...)``. Used by
  pychaste. Such a layout may also carry an ``exclude`` list of wrapped names
  that are deliberately not exposed (e.g. abstract base classes): they are still
  registered in the compiled extension - concrete subclasses depend on that - but
  are kept out of the Python package namespace. genpackage does not warn that an
  excluded name is unplaced, but does warn if one is nonetheless assigned to a
  subpackage (i.e. exposed after all).

Usage::

    cppwg genpackage --model wrapper/cppwg_package_model.json --layout package_layout.yaml
"""

import argparse
import json
import os
import sys

from cppwg.utils.utils import write_file_if_changed


GENERATED_HEADER = (
    '"""Generated by cppwg genpackage - do not edit.\n'
    "\n"
    "Compiled-extension imports and TemplateClass subscript stubs for this\n"
    "subpackage. Hand-written code (TemplateMethod attachments, package init,\n"
    'curation) belongs in the sibling __init__.py, which does `from ._generated\n'
    'import *`.\n'
    '"""\n'
)


FLATTEN_HEADER = (
    '"""Generated by cppwg genpackage - do not edit.\n'
    "\n"
    "Re-exports every wrapped class, enum and free function from the subpackages\n"
    "into the top-level package namespace, so `package.ClassName` works as well\n"
    "as `package.subpackage.ClassName`. Importing this imports the subpackages.\n"
    "The hand-written __init__.py does `from ._generated import *` and adds the\n"
    "bespoke top-level pieces (package init, etc.).\n"
    '"""\n'
)


def _render_key(args: list[str]) -> str:
    """Render a template-argument list as a Python tuple literal of strings.

    e.g. ``["2"]`` -> ``("2",)`` and ``["Cell", "2"]`` -> ``("Cell", "2")``.
    Matches _syntax._normalize_key, which normalizes keys to string tuples. Each
    value is rendered with ``json.dumps`` so any special characters are escaped
    into a valid (double-quoted) Python string literal.
    """
    inner = ", ".join(json.dumps(arg) for arg in args)
    if len(args) == 1:
        inner += ","
    return f"({inner})"


def _build_cpp_to_pyname(model: dict) -> dict:
    """Map each wrapped instantiation's C++ type string to its Python class name.

    e.g. ``PottsMesh<2> -> PottsMesh_2``. Used to key a template argument that is
    itself a wrapped templated type (``MeshFactory<PottsMesh<2>>``) by the Python
    concrete class name, so ``MeshFactory[PottsMesh[2]]`` resolves: ``PottsMesh[2]``
    is the ``PottsMesh_2`` class and ``_normalize_key`` keys it by its ``__name__``.

    Keyed by the instantiation's real C++ type name (``cpp_name``) so a class with
    a name_override (whose Python name differs from its C++ name) still resolves -
    including an untemplated renamed class (``OldName`` exposed as ``NewName``)
    used as a template argument. Older models without ``cpp_name`` fall back to
    reconstructing it from the base name and arguments (templated only).
    """
    index = {}
    for module in model["modules"]:
        for class_info in module["classes"]:
            for inst in class_info["instantiations"]:
                cpp = inst.get("cpp_name")
                if cpp is None and inst["args"]:
                    # Older model without cpp_name: reconstruct base<args>. An
                    # untemplated class in such a model carries no C++ name, so
                    # it cannot be indexed.
                    cpp = f'{class_info["base"]}<{",".join(inst["args"])}>'
                if cpp is not None:
                    index[cpp] = inst["py_name"]
    return index


def _render_template_stub(
    base: str,
    instantiations: list[dict],
    diagonal_shorthand: bool = False,
    cpp_to_pyname: dict = None,
) -> str:
    """Render a ``class <base>(TemplateClass)`` stub for a templated class.

    A template argument that is itself a wrapped templated type is keyed by its
    Python concrete class name via ``cpp_to_pyname`` (``PottsMesh<2>`` ->
    ``PottsMesh_2``), so ``MeshFactory[PottsMesh[2]]`` resolves.

    When ``diagonal_shorthand`` is set, a multi-argument instantiation whose
    arguments are all equal (a "diagonal", e.g. ``Element<2, 2>``) also gets a
    single-argument alias key (``Element[2] -> Element_2_2``). This is an
    opt-in Python-layer convenience some packages (pychaste) adopt for their
    ``<ELEMENT_DIM, SPACE_DIM>``-style classes; others (the cells example) keep
    the explicit multi-argument form only.
    """
    cpp_to_pyname = cpp_to_pyname or {}
    lines = [f"class {base}(TemplateClass):", "    _instantiations = {"]
    for inst in instantiations:
        args = [cpp_to_pyname.get(arg, arg) for arg in inst["args"]]
        lines.append(f'        {_render_key(args)}: {inst["py_name"]},')
        if diagonal_shorthand and len(args) > 1 and len(set(args)) == 1:
            lines.append(f'        {_render_key(args[:1])}: {inst["py_name"]},')
    lines.append("    }")
    return "\n".join(lines)


def render_generated_module(
    package: str,
    compiled_import: str,
    classes: list[dict],
    templated_classes: list[dict],
    diagonal_shorthand: bool = False,
    cpp_to_pyname: dict = None,
) -> str:
    """
    Render a subpackage's ``_generated.py`` content.

    Parameters
    ----------
    package : str
        The Python import root (e.g. ``pyshapes``, ``chaste``), used to import
        the shared ``_syntax`` helper.
    compiled_import : str
        The import statement pulling in the compiled extension's names.
    classes : list[dict]
        The subpackage's classes (from the model); used to know whether any
        TemplateClass import is needed.
    templated_classes : list[dict]
        The subset that is templated, each rendered as a stub.

    Returns
    -------
    str
        The file content (ending with a newline).
    """
    # Emit black-style output directly, the way the C++ templates emit clean C++:
    # docstring, one blank line, the imports, then each stub separated by two
    # blank lines. cppwg runs no formatter, so the layout built here is final.
    lines = [GENERATED_HEADER.rstrip("\n"), "", compiled_import]
    if templated_classes:
        lines.append(f"from {package}._syntax import TemplateClass")
    for class_info in templated_classes:
        lines.extend(["", ""])  # two blank lines before each top-level class
        lines.append(
            _render_template_stub(
                class_info["base"],
                class_info["instantiations"],
                diagonal_shorthand,
                cpp_to_pyname,
            )
        )
    return "\n".join(lines) + "\n"


def _concrete_py_names(class_info: dict) -> list[str]:
    """Return the concrete py_names of a class's instantiations."""
    return [inst["py_name"] for inst in class_info["instantiations"]]


def _explicit_import(package: str, compiled_module: str, names: list[str]) -> str:
    """Render an import of ``names`` from the shared compiled extension.

    With no names (an empty subpackage, or one whose names are all absent from
    the model) a ``from ... import ()`` list would be empty and invalid Python,
    so import the extension module itself instead, keeping the file valid. The
    import is aliased to a private name: a plain ``import package.extension``
    binds the top-level ``package`` name, which the sibling __init__'s
    ``from ._generated import *`` would then leak into the package API.
    """
    if not names:
        return f"import {package}.{compiled_module} as _extension  # noqa: F401"
    body = "".join(f"    {name},\n" for name in sorted(names))
    return f"from {package}.{compiled_module} import (\n{body})"


def _write_generated(path: str, content: str, overwrite: bool) -> str:
    """Write a ``_generated.py`` (creating parent dirs) and return its abspath.

    Reports whether the file was written or left unchanged. The returned path
    lets the caller record which outputs are live, so stale ones can be flagged
    (see ``_warn_orphans``).
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if write_file_if_changed(path, content, overwrite):
        print(f"wrote {path}")
    else:
        print(f"unchanged {path}")
    return os.path.abspath(path)


def generate_module_per_subpackage(model: dict, layout: dict, overwrite: bool) -> list:
    """Emit one ``_generated.py`` per cppwg module (each owns its own extension).

    Returns the list of files written, so the caller can flag orphaned outputs.
    """
    package = layout.get("package", model["package"])
    package_root = layout["package_root"]
    module_dirs = layout.get("module_dirs", {})
    diagonal_shorthand = layout.get("diagonal_shorthand", False)
    cpp_to_pyname = _build_cpp_to_pyname(model)

    # `exclude` cannot be honored here: a module-per-subpackage layout exposes
    # each module wholesale via `from .<module> import *`, so individual names
    # cannot be held back at the Python layer. It is only meaningful for the
    # shared-module split (explicit per-name membership).
    if layout.get("exclude"):
        print("warning: 'exclude' is only honored for shared-module-split layouts; "
              "ignoring it for this module-per-subpackage layout", file=sys.stderr)

    written = []
    for module in model["modules"]:
        # The subpackage directory (relative to package_root); default = module
        # name, overridable (e.g. a single "all" module living at the root).
        subdir = module_dirs.get(module["name"], module["name"])
        compiled_import = f"from .{module['compiled_module']} import *"
        templated = [c for c in module["classes"] if c["templated"]]
        content = render_generated_module(
            package,
            compiled_import,
            module["classes"],
            templated,
            diagonal_shorthand,
            cpp_to_pyname,
        )
        path = os.path.join(package_root, subdir, "_generated.py")
        written.append(_write_generated(path, content, overwrite))
    return written


def generate_shared_module_split(model: dict, layout: dict, overwrite: bool) -> list:
    """Emit a ``_generated.py`` per subpackage, splitting one shared extension.

    Returns the list of files written, so the caller can flag orphaned outputs.
    """
    package = layout.get("package", model["package"])
    package_root = layout["package_root"]
    compiled_module = layout["compiled_module"]
    diagonal_shorthand = layout.get("diagonal_shorthand", False)
    cpp_to_pyname = _build_cpp_to_pyname(model)
    written = []

    # Index every wrapped entity across the model by name so a layout entry can
    # be matched to a class (with its instantiations), an enum or a free function.
    classes_by_base = {}
    other_names = set()
    enum_exports = {}  # enum name -> enumerators it binds at module scope
    for module in model["modules"]:
        for class_info in module["classes"]:
            classes_by_base[class_info["base"]] = class_info
        for name in module["enums"] + module["free_functions"]:
            other_names.add(name)
        enum_exports.update(module.get("enum_exports", {}))

    assigned = set()
    flatten_names = {}  # subpackage -> the top-level names it exposes (issue #73)
    for subpkg, names in layout["subpackages"].items():
        classes = []
        import_names = []
        exported = []
        for name in names:
            assigned.add(name)
            if name in classes_by_base:
                class_info = classes_by_base[name]
                classes.append(class_info)
                import_names.extend(_concrete_py_names(class_info))
                exported.append(name)
            elif name in other_names:
                import_names.append(name)
                exported.append(name)
                # A value-exporting enum also binds its enumerators at module
                # scope; import/re-export them alongside the enum so e.g.
                # subpackage.CIRCLE keeps working under the split.
                for enumerator in enum_exports.get(name, []):
                    import_names.append(enumerator)
                    exported.append(enumerator)
            else:
                print(f"warning: '{name}' ({subpkg}) not found in model", file=sys.stderr)

        templated = [c for c in classes if c["templated"]]
        compiled_import = _explicit_import(package, compiled_module, import_names)
        content = render_generated_module(
            package,
            compiled_import,
            classes,
            templated,
            diagonal_shorthand,
            cpp_to_pyname,
        )
        path = os.path.join(package_root, subpkg, "_generated.py")
        written.append(_write_generated(path, content, overwrite))
        flatten_names[subpkg] = exported

    # Classes intentionally left unexposed (e.g. abstract base classes, which
    # should not be instantiated or subclassed from Python). Listing them in the
    # layout's `exclude` makes their absence from every subpackage deliberate
    # rather than an oversight, and lets exposing one later be flagged (below).
    excluded = set(layout.get("exclude", []))
    known = set(classes_by_base) | other_names

    # Flag any wrapped class neither placed in a subpackage nor explicitly
    # excluded, so nothing is silently dropped when the config gains a class.
    for name in sorted(known - assigned - excluded):
        print(f"warning: '{name}' is wrapped but not assigned to a subpackage",
              file=sys.stderr)

    # Flag an excluded name that is nonetheless assigned to a subpackage: it is
    # exposed despite being marked unexposed. Intersect with `known`: a name
    # assigned but absent from the model was never actually imported (it already
    # draws "not found in model" and the stale-entry warning below), so it is not
    # exposed and must not be reported here.
    for name in sorted(excluded & assigned & known):
        print(f"warning: '{name}' is in the layout 'exclude' list but is also "
              f"assigned to a subpackage, so it is exposed", file=sys.stderr)

    # Flag a stale exclude entry (not a wrapped entity) - likely a class that was
    # renamed or removed - so the exclude list is kept in step with the wrappers.
    for name in sorted(excluded - known):
        print(f"warning: '{name}' is in the layout 'exclude' list but is not a "
              f"wrapped class, enum or free function in the model", file=sys.stderr)

    if layout.get("flatten_to_root"):
        written.append(
            generate_root_flatten(package, package_root, flatten_names, overwrite)
        )
    return written


def generate_root_flatten(
    package: str, package_root: str, flatten_names: dict, overwrite: bool
) -> str:
    """Emit a top-level ``_generated.py`` re-exporting every subpackage's names.

    Gives ``package.ClassName`` in addition to ``package.subpackage.ClassName``
    (issue #73). Names are expected to be unique across subpackages; a clash is
    warned about (the last subpackage's binding would win at import time).
    """
    owner = {}  # name -> subpackage that first exported it, for a clash check
    for subpkg in sorted(flatten_names):
        for name in flatten_names[subpkg]:
            if name in owner:
                print(
                    f"warning: '{name}' is exported by both '{owner[name]}' and "
                    f"'{subpkg}'; top-level {package}.{name} would be ambiguous",
                    file=sys.stderr,
                )
            else:
                owner[name] = subpkg

    lines = [FLATTEN_HEADER.rstrip("\n"), ""]
    for subpkg in sorted(flatten_names):
        names = flatten_names[subpkg]
        if names:
            lines.append(_explicit_import(package, subpkg, names))
    lines.append("")
    lines.append("__all__ = [")
    for name in sorted(owner):
        lines.append(f'    "{name}",')
    lines.append("]")
    content = "\n".join(lines) + "\n"
    return _write_generated(
        os.path.join(package_root, "_generated.py"), content, overwrite
    )


def _warn_orphans(package_root: str, written: list) -> None:
    """Warn about generated files under ``package_root`` this run did not write.

    A ``_generated.py`` carrying the do-not-edit banner but no longer a target
    means its module/subpackage was removed from the config. cppwg only ever
    generates ``_generated.py`` (never the hand-written ``__init__.py``), so it
    cannot fully remove the orphaned subpackage; it flags it for the user to
    delete rather than silently leaving stale bindings or deleting their files.
    """
    written = {os.path.abspath(p) for p in written}
    banner = "Generated by cppwg genpackage"
    for dirpath, _dirs, files in os.walk(package_root):
        if "_generated.py" not in files:
            continue
        path = os.path.abspath(os.path.join(dirpath, "_generated.py"))
        if path in written:
            continue
        with open(path) as generated_file:
            if banner not in generated_file.read(200):
                continue  # not one of ours -> never touch it
        print(
            f"warning: {path} is generated but no longer a target; its "
            "module/subpackage was removed - delete the containing directory",
            file=sys.stderr,
        )


def main(argv=None) -> int:
    """Entry point: read the model + layout and write the _generated.py files."""
    parser = argparse.ArgumentParser(prog="cppwg genpackage", description=__doc__)
    parser.add_argument(
        "--model", required=True, help="Path to cppwg_package_model.json (from cppwg)."
    )
    parser.add_argument(
        "--layout", required=True, help="Path to the Python package-layout file (YAML)."
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Rewrite files even if unchanged.",
    )
    args = parser.parse_args(argv)

    import yaml

    with open(args.model) as model_file:
        model = json.load(model_file)  # the model is JSON (see cppwg.utils.constants)
    with open(args.layout) as layout_file:
        layout = yaml.safe_load(layout_file)

    # Resolve a relative package_root against the layout's own directory, so a
    # layout is portable regardless of the caller's working directory.
    if not os.path.isabs(layout["package_root"]):
        layout_dir = os.path.dirname(os.path.abspath(args.layout))
        layout["package_root"] = os.path.normpath(
            os.path.join(layout_dir, layout["package_root"])
        )

    if layout.get("subpackages"):
        written = generate_shared_module_split(model, layout, args.overwrite)
    else:
        written = generate_module_per_subpackage(model, layout, args.overwrite)
    _warn_orphans(layout["package_root"], written)
    return 0
