#!/usr/bin/env python3
"""Generate the Python package layer (``_generated.py``) for a cppwg project.

cppwg generates the C++/pybind11 wrappers and, alongside them, a YAML model of
what it produced (``cppwg_model.yaml`` in the wrapper root - see
``cppwg.utils.python_model``). This standalone script turns that model, plus a
small layout manifest, into a ``_generated.py`` per Python subpackage: the
compiled-extension import and the ``TemplateClass`` subscript stubs
(``Point[2] -> Point_2``). It never touches the hand-written ``__init__.py``,
which does ``from ._generated import *`` and adds the bespoke pieces
(``TemplateMethod`` attachments, package ``init()``, curation, comments).

Two layouts:

* module-per-subpackage (default): each cppwg module becomes a subpackage that
  owns its own compiled extension, imported with ``from .<module> import *``.
  Used by the shapes/cells examples.
* shared-module split: one compiled extension (e.g. ``_pychaste_all``) is split
  into several subpackages by a manifest that lists which names each owns;
  imported explicitly with ``from <package>.<module> import (...)``. Used by
  pychaste.

Usage::

    cppwg_initgen.py --model wrapper/cppwg_model.yaml --manifest py_layout.yaml
"""

import argparse
import os
import sys

# Reuse cppwg's idempotent writer when importable; fall back to a local copy so
# the script also runs standalone (e.g. from a build tree without cppwg on the
# path).
try:
    from cppwg.utils.utils import write_file_if_changed
except ImportError:  # pragma: no cover - exercised only without cppwg installed

    def write_file_if_changed(filepath, content, overwrite=False):
        """Write content unless an identical file already exists."""
        if not overwrite and os.path.isfile(filepath):
            with open(filepath) as in_file:
                if in_file.read() == content:
                    return False
        with open(filepath, "w") as out_file:
            out_file.write(content)
        return True


GENERATED_HEADER = (
    '"""Generated by tools/cppwg_initgen.py - do not edit.\n'
    "\n"
    "Compiled-extension imports and TemplateClass subscript stubs for this\n"
    "subpackage. Hand-written code (TemplateMethod attachments, package init,\n"
    'curation) belongs in the sibling __init__.py, which does `from ._generated\n'
    'import *`.\n'
    '"""\n'
)


FLATTEN_HEADER = (
    '"""Generated by tools/cppwg_initgen.py - do not edit.\n'
    "\n"
    "Re-exports every wrapped class, enum and free function from the subpackages\n"
    "into the top-level package namespace, so `package.ClassName` works as well\n"
    "as `package.subpackage.ClassName`. Importing this imports the subpackages.\n"
    "The hand-written __init__.py does `from ._generated import *` and adds the\n"
    "bespoke top-level pieces (package init, etc.).\n"
    '"""\n'
)


def _key_repr(args: list[str]) -> str:
    """Render a template-argument list as a Python tuple literal of strings.

    e.g. ``["2"]`` -> ``("2",)`` and ``["Cell", "2"]`` -> ``("Cell", "2")``.
    Matches _syntax._normalize_key, which normalizes keys to string tuples.
    """
    inner = ", ".join(f'"{arg}"' for arg in args)
    if len(args) == 1:
        inner += ","
    return f"({inner})"


def _stub_source(
    base: str, instantiations: list[dict], diagonal_shorthand: bool = False
) -> str:
    """Render a ``class <base>(TemplateClass)`` stub for a templated class.

    When ``diagonal_shorthand`` is set, a multi-argument instantiation whose
    arguments are all equal (a "diagonal", e.g. ``Element<2, 2>``) also gets a
    single-argument alias key (``Element[2] -> Element_2_2``). This is an
    opt-in Python-layer convenience some packages (pychaste) adopt for their
    ``<ELEMENT_DIM, SPACE_DIM>``-style classes; others (the cells example) keep
    the explicit multi-argument form only.
    """
    lines = [f"class {base}(TemplateClass):", "    _instantiations = {"]
    for inst in instantiations:
        args = inst["args"]
        lines.append(f'        {_key_repr(args)}: {inst["py_name"]},')
        if diagonal_shorthand and len(args) > 1 and len(set(args)) == 1:
            lines.append(f'        {_key_repr(args[:1])}: {inst["py_name"]},')
    lines.append("    }")
    return "\n".join(lines)


def render_generated_module(
    package: str,
    compiled_import: str,
    classes: list[dict],
    templated_classes: list[dict],
    diagonal_shorthand: bool = False,
) -> str:
    """
    Render a subpackage's ``_generated.py`` content.

    Parameters
    ----------
    package : str
        The Python import root (e.g. ``pyshapes``, ``chaste``), used to import
        the shared ``_syntax`` helper.
    compiled_import : str
        The import statement pulling in the compiled extension's names.
    classes : list[dict]
        The subpackage's classes (from the model); used to know whether any
        TemplateClass import is needed.
    templated_classes : list[dict]
        The subset that is templated, each rendered as a stub.

    Returns
    -------
    str
        The file content (ending with a newline).
    """
    # Build black-clean output: docstring, one blank line, the imports, then each
    # stub separated by two blank lines.
    lines = [GENERATED_HEADER.rstrip("\n"), "", compiled_import]
    if templated_classes:
        lines.append(f"from {package}._syntax import TemplateClass")
    for class_info in templated_classes:
        lines.extend(["", ""])  # two blank lines before each top-level class
        lines.append(
            _stub_source(
                class_info["base"],
                class_info["instantiations"],
                diagonal_shorthand,
            )
        )
    return "\n".join(lines) + "\n"


def _concrete_names(class_info: dict) -> list[str]:
    """Return the concrete py_names of a class's instantiations."""
    return [inst["py_name"] for inst in class_info["instantiations"]]


def _explicit_import(package: str, compiled_module: str, names: list[str]) -> str:
    """Render an explicit ``from <package>.<compiled> import (...)`` statement."""
    body = "".join(f"    {name},\n" for name in sorted(names))
    return f"from {package}.{compiled_module} import (\n{body})"


def _format(content: str) -> str:
    """Format with black when available, so output is stable and idempotent.

    Long instantiation keys (e.g. pychaste's CellsGenerator) exceed black's line
    length and must be wrapped exactly as black would, or a project's
    ``black --check`` / ``git diff`` reproducibility gate fails. When black is
    not installed the content is written as-is (still valid Python).
    """
    try:
        import black
    except ImportError:  # pragma: no cover - only when black is absent
        return content
    return black.format_str(content, mode=black.Mode())


def _write_generated(path: str, content: str, overwrite: bool) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    content = _format(content)
    if write_file_if_changed(path, content, overwrite):
        print(f"wrote {path}")
    else:
        print(f"unchanged {path}")


def generate_module_per_subpackage(model: dict, manifest: dict, overwrite: bool):
    """Emit one ``_generated.py`` per cppwg module (each owns its own extension)."""
    package = manifest.get("package", model["package"])
    package_root = manifest["package_root"]
    module_dirs = manifest.get("module_dirs", {})
    diagonal_shorthand = manifest.get("diagonal_shorthand", False)

    for module in model["modules"]:
        # The subpackage directory (relative to package_root); default = module
        # name, overridable (e.g. a single "all" module living at the root).
        subdir = module_dirs.get(module["name"], module["name"])
        compiled_import = f"from .{module['compiled_module']} import *"
        templated = [c for c in module["classes"] if c["templated"]]
        content = render_generated_module(
            package, compiled_import, module["classes"], templated, diagonal_shorthand
        )
        path = os.path.join(package_root, subdir, "_generated.py")
        _write_generated(path, content, overwrite)


def generate_shared_module_split(model: dict, manifest: dict, overwrite: bool):
    """Emit a ``_generated.py`` per subpackage, splitting one shared extension."""
    package = manifest.get("package", model["package"])
    package_root = manifest["package_root"]
    compiled_module = manifest["compiled_module"]
    diagonal_shorthand = manifest.get("diagonal_shorthand", False)

    # Index every wrapped entity across the model by name so a manifest entry can
    # be matched to a class (with its instantiations), an enum or a free function.
    classes_by_base = {}
    other_names = set()
    for module in model["modules"]:
        for class_info in module["classes"]:
            classes_by_base[class_info["base"]] = class_info
        for name in module["enums"] + module["free_functions"]:
            other_names.add(name)

    assigned = set()
    flatten_names = {}  # subpackage -> the top-level names it exposes (issue #73)
    for subpkg, names in manifest["subpackages"].items():
        classes = []
        import_names = []
        exported = []
        for name in names:
            assigned.add(name)
            if name in classes_by_base:
                class_info = classes_by_base[name]
                classes.append(class_info)
                import_names.extend(_concrete_names(class_info))
                exported.append(name)
            elif name in other_names:
                import_names.append(name)
                exported.append(name)
            else:
                print(f"warning: '{name}' ({subpkg}) not found in model", file=sys.stderr)

        templated = [c for c in classes if c["templated"]]
        compiled_import = _explicit_import(package, compiled_module, import_names)
        content = render_generated_module(
            package, compiled_import, classes, templated, diagonal_shorthand
        )
        path = os.path.join(package_root, subpkg, "_generated.py")
        _write_generated(path, content, overwrite)
        flatten_names[subpkg] = exported

    # Flag any wrapped class not placed in a subpackage, so nothing is silently
    # dropped when the config gains a class.
    unplaced = sorted(set(classes_by_base) | other_names)
    for name in unplaced:
        if name not in assigned:
            print(f"warning: '{name}' is wrapped but not assigned to a subpackage",
                  file=sys.stderr)

    if manifest.get("flatten_to_root"):
        generate_root_flatten(package, package_root, flatten_names, overwrite)


def generate_root_flatten(
    package: str, package_root: str, flatten_names: dict, overwrite: bool
) -> None:
    """Emit a top-level ``_generated.py`` re-exporting every subpackage's names.

    Gives ``package.ClassName`` in addition to ``package.subpackage.ClassName``
    (issue #73). Names are expected to be unique across subpackages; a clash is
    warned about (the last subpackage's binding would win at import time).
    """
    owner = {}  # name -> subpackage that first exported it, for a clash check
    for subpkg in sorted(flatten_names):
        for name in flatten_names[subpkg]:
            if name in owner:
                print(
                    f"warning: '{name}' is exported by both '{owner[name]}' and "
                    f"'{subpkg}'; top-level {package}.{name} would be ambiguous",
                    file=sys.stderr,
                )
            else:
                owner[name] = subpkg

    lines = [FLATTEN_HEADER.rstrip("\n"), ""]
    for subpkg in sorted(flatten_names):
        names = flatten_names[subpkg]
        if names:
            lines.append(_explicit_import(package, subpkg, names))
    lines.append("")
    lines.append("__all__ = [")
    for name in sorted(owner):
        lines.append(f'    "{name}",')
    lines.append("]")
    content = "\n".join(lines) + "\n"
    _write_generated(os.path.join(package_root, "_generated.py"), content, overwrite)


def main(argv=None) -> int:
    """Entry point: read the model + manifest and write the _generated.py files."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model", required=True, help="Path to cppwg_model.yaml (from cppwg)."
    )
    parser.add_argument(
        "--manifest", required=True, help="Path to the Python layout manifest (YAML)."
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Rewrite files even if unchanged.",
    )
    args = parser.parse_args(argv)

    import yaml

    with open(args.model) as model_file:
        model = yaml.safe_load(model_file)
    with open(args.manifest) as manifest_file:
        manifest = yaml.safe_load(manifest_file)

    # Resolve a relative package_root against the manifest's own directory, so a
    # manifest is portable regardless of the caller's working directory.
    if not os.path.isabs(manifest["package_root"]):
        manifest_dir = os.path.dirname(os.path.abspath(args.manifest))
        manifest["package_root"] = os.path.normpath(
            os.path.join(manifest_dir, manifest["package_root"])
        )

    if manifest.get("subpackages"):
        generate_shared_module_split(model, manifest, args.overwrite)
    else:
        generate_module_per_subpackage(model, manifest, args.overwrite)
    return 0


if __name__ == "__main__":
    sys.exit(main())
