name: build-and-test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyyaml pygccxml castxml

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/cppwg:$PYTHONPATH" >> ${GITHUB_ENV}

      - name: Generate Wrappers
        run: |
          python shapes/wrapper/generate.py \
          --source_root shapes/src/ \
          --wrapper_root shapes/wrapper/ \
          --castxml_binary $Python3_ROOT_DIR/bin/castxml \
          --package_info shapes/wrapper/package_info.yaml \
          --includes shapes/src/
