name: test-unit

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "**"

concurrency:
  group: test-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install cppwg
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[dev]

      - name: Run unit tests
        run: python3 -m pytest tests/
